In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import re
import pandas as pd
#from datasets import load_dataset
import time
import pickle
from tqdm import tqdm

## GPT HELP

In [3]:
df1 = pd.read_pickle("/content/drive/MyDrive/NLP_project/Abhishek (Mutli tool Chained- hotpot)/First_QAWC.pkl")
df1

,Q,A,W,C
0,"The Dutch-Belgian television series that ""Hous...",6,House of Anubis > House of Anubis is a mystery...,First search for [Het Huis Anubis first aired ...
1,What would be the length of the track where th...,10.213,2013 Liqui Moly Bathurst 12 Hour > The 2013 Li...,First search [Mount Panorama Circuit -Wiki-> y...
2,"The 1988 American comedy film, The Great Outdo...",4,The Great Outdoors (film) > The Great Outdoors...,First Search [Annette Bening -Wiki-> y1]. She ...
3,"Dua Lipa, an English singer, songwriter and mo...",17,Dua Lipa > Her self-titled debut studio album...,First Search [ Dua Lipa New Rules release -Wik...
4,How old would be the female main protagonist o...,22,Catching Fire > Catching Fire is a 2009 scienc...,First Search for [Catching Fire Suzanne Collin...
...,...,...,...,...
13907,A Grupė is the highest level of women's volley...,30000,A Grupė (Volleyball) > The A Grupė is highest ...,First search for [A Grupe -Wiki-> y1]. Now sea...
13908,The 1968 Baltimore Orioles season included a r...,35,1968 Baltimore Orioles season > The team was ...,First search for [1968 Baltimore Orioles seaso...
13909,How many stories are in the hotel that hosted ...,600,10th IIFA Awards > The 10th International Indi...,First search for [10th IIFA Awards -Wiki-> y1]...
13931,Multiply the number of years that Cocteau Twin...,10008,Cocteau Twins > Cocteau Twins were a Scottish ...,First Search [Cocteau Twins -Wiki-> y1]. Band ...
13932,Find the number of years that passed from the ...,2,Vietnam national cricket team > The Vietnam na...,First Search [Vietnam national cricket team -W...

In [4]:
first100 = df1.iloc[:500]
first100

,Q,A,W,C
0,"The Dutch-Belgian television series that ""Hous...",6,House of Anubis > House of Anubis is a mystery...,First search for [Het Huis Anubis first aired ...
1,What would be the length of the track where th...,10.213,2013 Liqui Moly Bathurst 12 Hour > The 2013 Li...,First search [Mount Panorama Circuit -Wiki-> y...
2,"The 1988 American comedy film, The Great Outdo...",4,The Great Outdoors (film) > The Great Outdoors...,First Search [Annette Bening -Wiki-> y1]. She ...
3,"Dua Lipa, an English singer, songwriter and mo...",17,Dua Lipa > Her self-titled debut studio album...,First Search [ Dua Lipa New Rules release -Wik...
4,How old would be the female main protagonist o...,22,Catching Fire > Catching Fire is a 2009 scienc...,First Search for [Catching Fire Suzanne Collin...
...,...,...,...,...
755,What would be the population of the city where...,103297,Lansing State Journal > The Lansing State Jour...,First search for [ Lansing State Journal -Wiki...
756,What year would the debut single of the singer...,2014,"3AM (Pull Up) > ""3am (Pull Up)"" is a song reco...",First search for [Charli XCX -Wiki-> y1]. Sear...
757,Between what years would Charles Hutchison and...,1925,Charles Hutchison > He appeared in 49 films b...,First search for [Charles Hutchison -Wiki-> y1...
758,How old would the American social entrepeneur ...,54,"Rachel Jacobs > Rachel Jacobs (October 3, 1975...",Search for [Rachel Jacobs -Wiki-> y1]. Search ...
759,What would be the number of studio album relea...,4,Signs of Light > Signs of Light is the third s...,Search for [The Head and the Heart -Wiki-> y1]...

In [5]:
prompt_examples="""1.
Q: The Dutch-Belgian television series that "House of Anubis" was based on first aired in how many years after 2000?
A: 6
W: House of Anubis > House of Anubis is a mystery television series developed for Nickelodeon based on the Dutch-Belgian television series "Het Huis Anubis". | Het Huis Anubis >  It first aired in September 2006 and the last episode was broadcast on December 4, 2009.
C: First search for [Het Huis Anubis first aired -Wiki-> y1]. First episode released in [y1 -QA(Which year was the fist episode aired ?)-> y2]. Number of years it aired after 2000 [y2 - 2000 = y3]. The answer is y3.

2.
Q: What would be the length of the track where the 2013 Liqui Moly Bathurst 12 Hour was staged, if it would have been 4km longer?
A: 10.213
W: 2013 Liqui Moly Bathurst 12 Hour > The 2013 Liqui Moly Bathurst 12 Hour was an endurance race for a variety of GT and touring car classes, including: GT3 cars, GT4 cars, Group 3E Series Production Cars and Dubai 24 Hour cars. | 2013 Liqui Moly Bathurst 12 Hour >  The event, which was staged at the Mount Panorama Circuit, near Bathurst, in New South Wales, Australia on 10 February 2013, was the eleventh running of the Bathurst 12 Hour. | Mount Panorama Circuit > Mount Panorama Circuit is a motor racing track located in Bathurst, New South Wales, Australia. | Mount Panorama Circuit >  The 6.213 km long track is technically a street circuit, and is a public road, with normal speed restrictions, when no racing events are being run, and there are many residences which can only be accessed from the circuit.
C: First search [Mount Panorama Circuit -Wiki-> y1]. Length of circuit is [y1 -QA(what is the length of Mount Panorama Circuit ?)-> y2]. Length after adding 4km will be [4 + y2 = y3]. The answer is y3.

3.
Q: The 1988 American comedy film, The Great Outdoors, starred a four-time Academy Award nominee, who received a star on the Hollywood Walk of Fame in how many years before 2010?
A: 4
W: The Great Outdoors (film) > The Great Outdoors is a 1988 American comedy film directed by Howard Deutch, and written and produced by John Hughes. | The Great Outdoors (film) >  It stars Dan Aykroyd, John Candy, Stephanie Faracy and Annette Bening in her film debut. | Annette Bening > Annette Carol Bening (born May 29, 1958) is an American actress. | Annette Bening >  She is a four-time Academy Award nominee; for "The Grifters" (1990), "American Beauty" (1999), "Being Julia" (2004) and "The Kids Are All Right" (2010). | Annette Bening >  In 2006, she received a star on the Hollywood Walk of Fame.
C: First Search [Annette Bening -Wiki-> y1]. She received star on the Hollywood Walk of Fame on [y1 -QA(When did she recieved star on Hollywood Walk of Fame ?)-> y2]. Number of years before 2010 [2010 - y2 = y3]. The answer is y3.

4.
Q: Dua Lipa, an English singer, songwriter and model, the album spawned the number-one single "New Rules" is a song by English singer Dua Lipa from her eponymous debut studio album, released in how many years after 2000?
A: 17
W: Dua Lipa >  Her self-titled debut studio album was released on 2 June 2017. | New Rules (song) > "New Rules" is a song by English singer Dua Lipa from her eponymous debut studio album (2017).
C: First Search [ Dua Lipa New Rules release -Wiki-> y1]. New rules was released in [y1 -QA(In which year was New Rules song released ?)-> y2]. Number of years from 2000 after its released is [y2 - 2000 = y3]. The answer is y3.

5.
Q: How old would be the female main protagonist of Catching Fire, if she was born 6 years before?
A: 22
W: Catching Fire > Catching Fire is a 2009 science fiction young adult novel by the American novelist Suzanne Collins, the second book in "The Hunger Games trilogy". | The Hunger Games (novel) >  It is written in the voice of 16-year-old Katniss Everdeen, who lives in the future, post-apocalyptic nation of Panem in North America.
C: First Search for [Catching Fire Suzanne Collins -Wiki-> y1]. Search for her age at that time [y1 -QA(What was the age of Katniss Everdeen at that time ?)-> y2]. She would how many years old is she was born 6 years before [y2 + 6 = y3]. The answer is y3.

6.
Q: How many years before 1947 was the creator of the current arrangement of the "Simpson's Theme" born?
A: 6
W: The Simpsons Theme > "The Simpsons" Theme", also referred to as "The Simpsons" Main Title Theme" in album releases, is the theme music of the animated television series "The Simpsons". | The Simpsons Theme >  The theme, as used for the opening sequence, was re-arranged during season 2, and the current arrangement by Alf Clausen was introduced at the beginning of the third season. | Alf Clausen > Alf Heiberg Clausen (born March 28, 1941) is an American film and television composer.
C: First find [Simpson's Theme creator -Wiki-> y1]. Now search for when was he born [y1 -QA(When was Alf Heiberg Clausen born ?)-> y2]. Now find how many years before 1947 he was born [1947 - y2 = y3]. The final answer is y3.

7.
Q: The American Pre-Code comedy film featuring an American actress, dancer, and singer, widely known for performing in films and RKO's musical films, was released in how many years after 1925?
A: 7
W: Hat Check Girl > Hat Check Girl is a 1932 American Pre-Code comedy film directed by Sidney Lanfield and written by Barry Conners and Philip Klein. | Hat Check Girl >  The film stars Sally Eilers, Ben Lyon, Ginger Rogers and Monroe Owsley. | Ginger Rogers > Ginger Rogers (born Virginia Katherine McMath; July 16, 1911 – April 25, 1995) was an American actress, dancer, and singer, widely known for performing in films and RKO's musical films, partnered with Fred Astaire.
C: First Search for [American Pre-Code comedy RKO musical film -Wiki-> y1]. Now search for year it was released [y1 -QA(When was Hat Check Girl Released ?)-> y2]. Now find number of years after 1925 it was released [y2 - 1925 = y3]. The answer is y3.

8.
Q: How many years after 1950 was the winner of the 2016 Marrakesh ePrix born?
A: 38
W: 2016 Marrakesh ePrix >  The 33-lap race was won by e.Dams-Renault driver Sébastien Buemi, who started from the seventh position. | Sébastien Buemi > Sébastien Olivier Buemi (born 31 October 1988) is a Swiss professional racing driver, who formerly competed for Scuderia Toro Rosso in Formula One.
C: First search for [2016 Marrakesh ePrix winner -Wiki-> y1]. Now search for when he was born [y1 -QA(When was Sébastien Buemi born ?)-> y2]. Now search for how many years after 1950 he was born so subtract [y2 - 1950 = y3]. The answer is y3.
"""

In [6]:
prompt_rows = first100[['Q','A','W']].to_dict('records')

In [7]:
gemini_prompt=f"""You are an agent that converts Questions, Answers, and corresponding Wikipedia Knowledge to a Chain of Abstractions. The intuition is to get to the Answer using the titles searched in the  Wikipedia knowledge.

Rules to generate C:
1.  You have 3 tools, Wiki, QA and Mathematical. Use **all tools** to derive C. Tool Explanations are:
	Wiki Tool to get relevant articles from Wikipedia. Format: [search query -Wiki-> search query output]
	QA tool to get the focused answer from the Wikipedia articles. Format:  [input context -QA(question)-> output]
  Mathematical tool solves any mathematical computes over the informtion returned from QA tool Format: [polynomial expression] eg:[y1 + 20 = y2]
2. W is formatted to put the title before '>' and content after '>' and separate articles using '|'.
3. Use the outputs from Wiki tool as input context for QA tool. And use QA tool output as input for mathematical tool The final answer is always output of Mathematical tool. **This is crucial** please try to follow this format
4. You can use page titles but cannot use page content information given in W to form Wiki search Queries.
5. You cannot use answer (A) in the tool queries directly.
6. You can only use first wikipedia title in the tool queries directly and cannot use any subsequent titles directly in tool queries
7. Utilize the Chain of Thought process from the Wikipedia Knowledge given. Learn what titles need to be searched in the Wiki tool and asked in the QA tool to get to the final answer. Conclude by ** The answer is <variable_name>.**

Your task to generate Abstractions(C)  for the given Question (Q) using the Wiki tool, the QA tool and the mathematical tool using the rules.

Examples to generate Chain of Abstraction( C)  given Q, A and W are:
### EXAMPLES
{prompt_examples}

### TASK
Now  generate C for the test examples below. Please Write '###DONE' when you have completed generating C for all of the examples below.
Respond in this format only:
Test Example <example number> C:

"""

def generate_continuation_gemini(prompt_rows):
    prompt = gemini_prompt

    for idx, row in enumerate(prompt_rows):
        prompt += f"Test Example {idx + 1}\n"
        prompt += f"Q: {row['Q']}\n"
        prompt += f"A: {row['A']}\n"
        prompt += f"W: {row['W']}\n"
        prompt += "\n"
    return prompt + "### RESPONSE\n"

##CREATE PROMPT

In [8]:
generated_dataset = [] #INITIALIZATION

In [134]:
selected_rows=prompt_rows[400:410] #CHOOSE ROWS

In [135]:
input_prompt=generate_continuation_gemini(selected_rows)
print(input_prompt)

You are an agent that converts Questions, Answers, and corresponding Wikipedia Knowledge to a Chain of Abstractions. The intuition is to get to the Answer using the titles searched in the  Wikipedia knowledge.

Rules to generate C:
1.  You have 3 tools, Wiki, QA and Mathematical. Use **all tools** to derive C. Tool Explanations are:
	Wiki Tool to get relevant articles from Wikipedia. Format: [search query -Wiki-> search query output]
	QA tool to get the focused answer from the Wikipedia articles. Format:  [input context -QA(question)-> output]
  Mathematical tool solves any mathematical computes over the informtion returned from QA tool Format: [polynomial expression] eg:[y1 + 20 = y2]
2. W is formatted to put the title before '>' and content after '>' and separate articles using '|'.
3. Use the outputs from Wiki tool as input context for QA tool. And use QA tool output as input for mathematical tool The final answer is always output of Mathematical tool. **This is crucial** please try to follow this format
4. You can use page titles but cannot use page content information given in W to form Wiki search Queries.
5. You cannot use answer (A) in the tool queries directly.
6. You can only use first wikipedia title in the tool queries directly and cannot use any subsequent titles directly in tool queries
7. Utilize the Chain of Thought process from the Wikipedia Knowledge given. Learn what titles need to be searched in the Wiki tool and asked in the QA tool to get to the final answer. Conclude by ** The answer is <variable_name>.**

Your task to generate Abstractions(C)  for the given Question (Q) using the Wiki tool, the QA tool and the mathematical tool using the rules.

Examples to generate Chain of Abstraction( C)  given Q, A and W are:
### EXAMPLES
1.
Q: The Dutch-Belgian television series that "House of Anubis" was based on first aired in how many years after 2000?
A: 6
W: House of Anubis > House of Anubis is a mystery television series developed for Nickelodeon based on the Dutch-Belgian television series "Het Huis Anubis". | Het Huis Anubis >  It first aired in September 2006 and the last episode was broadcast on December 4, 2009.
C: First search for [Het Huis Anubis first aired -Wiki-> y1]. First episode released in [y1 -QA(Which year was the fist episode aired ?)-> y2]. Number of years it aired after 2000 [y2 - 2000 = y3]. The answer is y3.

2.
Q: What would be the length of the track where the 2013 Liqui Moly Bathurst 12 Hour was staged, if it would have been 4km longer?
A: 10.213
W: 2013 Liqui Moly Bathurst 12 Hour > The 2013 Liqui Moly Bathurst 12 Hour was an endurance race for a variety of GT and touring car classes, including: GT3 cars, GT4 cars, Group 3E Series Production Cars and Dubai 24 Hour cars. | 2013 Liqui Moly Bathurst 12 Hour >  The event, which was staged at the Mount Panorama Circuit, near Bathurst, in New South Wales, Australia on 10 February 2013, was the eleventh running of the Bathurst 12 Hour. | Mount Panorama Circuit > Mount Panorama Circuit is a motor racing track located in Bathurst, New South Wales, Australia. | Mount Panorama Circuit >  The 6.213 km long track is technically a street circuit, and is a public road, with normal speed restrictions, when no racing events are being run, and there are many residences which can only be accessed from the circuit.
C: First search [Mount Panorama Circuit -Wiki-> y1]. Length of circuit is [y1 -QA(what is the length of Mount Panorama Circuit ?)-> y2]. Length after adding 4km will be [4 + y2 = y3]. The answer is y3.

3.
Q: The 1988 American comedy film, The Great Outdoors, starred a four-time Academy Award nominee, who received a star on the Hollywood Walk of Fame in how many years before 2010?
A: 4
W: The Great Outdoors (film) > The Great Outdoors is a 1988 American comedy film directed by Howard Deutch, and written and produced by John Hughes. | The Great Outdoors (film) >  It stars Dan Aykroyd, John Candy, Stephanie Faracy and Annette Bening in her film debut. | Annette Bening > Annette Carol Bening (born May 29, 1958) is an American actress. | Annette Bening >  She is a four-time Academy Award nominee; for "The Grifters" (1990), "American Beauty" (1999), "Being Julia" (2004) and "The Kids Are All Right" (2010). | Annette Bening >  In 2006, she received a star on the Hollywood Walk of Fame.
C: First Search [Annette Bening -Wiki-> y1]. She received star on the Hollywood Walk of Fame on [y1 -QA(When did she recieved star on Hollywood Walk of Fame ?)-> y2]. Number of years before 2010 [2010 - y2 = y3]. The answer is y3.

4.
Q: Dua Lipa, an English singer, songwriter and model, the album spawned the number-one single "New Rules" is a song by English singer Dua Lipa from her eponymous debut studio album, released in how many years after 2000?
A: 17
W: Dua Lipa >  Her self-titled debut studio album was released on 2 June 2017. | New Rules (song) > "New Rules" is a song by English singer Dua Lipa from her eponymous debut studio album (2017).
C: First Search [ Dua Lipa New Rules release -Wiki-> y1]. New rules was released in [y1 -QA(In which year was New Rules song released ?)-> y2]. Number of years from 2000 after its released is [y2 - 2000 = y3]. The answer is y3.

5.
Q: How old would be the female main protagonist of Catching Fire, if she was born 6 years before?
A: 22
W: Catching Fire > Catching Fire is a 2009 science fiction young adult novel by the American novelist Suzanne Collins, the second book in "The Hunger Games trilogy". | The Hunger Games (novel) >  It is written in the voice of 16-year-old Katniss Everdeen, who lives in the future, post-apocalyptic nation of Panem in North America.
C: First Search for [Catching Fire Suzanne Collins -Wiki-> y1]. Search for her age at that time [y1 -QA(What was the age of Katniss Everdeen at that time ?)-> y2]. She would how many years old is she was born 6 years before [y2 + 6 = y3]. The answer is y3.

6.
Q: How many years before 1947 was the creator of the current arrangement of the "Simpson's Theme" born?
A: 6
W: The Simpsons Theme > "The Simpsons" Theme", also referred to as "The Simpsons" Main Title Theme" in album releases, is the theme music of the animated television series "The Simpsons". | The Simpsons Theme >  The theme, as used for the opening sequence, was re-arranged during season 2, and the current arrangement by Alf Clausen was introduced at the beginning of the third season. | Alf Clausen > Alf Heiberg Clausen (born March 28, 1941) is an American film and television composer.
C: First find [Simpson's Theme creator -Wiki-> y1]. Now search for when was he born [y1 -QA(When was Alf Heiberg Clausen born ?)-> y2]. Now find how many years before 1947 he was born [1947 - y2 = y3]. The final answer is y3.

7.
Q: The American Pre-Code comedy film featuring an American actress, dancer, and singer, widely known for performing in films and RKO's musical films, was released in how many years after 1925?
A: 7
W: Hat Check Girl > Hat Check Girl is a 1932 American Pre-Code comedy film directed by Sidney Lanfield and written by Barry Conners and Philip Klein. | Hat Check Girl >  The film stars Sally Eilers, Ben Lyon, Ginger Rogers and Monroe Owsley. | Ginger Rogers > Ginger Rogers (born Virginia Katherine McMath; July 16, 1911 – April 25, 1995) was an American actress, dancer, and singer, widely known for performing in films and RKO's musical films, partnered with Fred Astaire.
C: First Search for [American Pre-Code comedy RKO musical film -Wiki-> y1]. Now search for year it was released [y1 -QA(When was Hat Check Girl Released ?)-> y2]. Now find number of years after 1925 it was released [y2 - 1925 = y3]. The answer is y3.

8.
Q: How many years after 1950 was the winner of the 2016 Marrakesh ePrix born?
A: 38
W: 2016 Marrakesh ePrix >  The 33-lap race was won by e.Dams-Renault driver Sébastien Buemi, who started from the seventh position. | Sébastien Buemi > Sébastien Olivier Buemi (born 31 October 1988) is a Swiss professional racing driver, who formerly competed for Scuderia Toro Rosso in Formula One.
C: First search for [2016 Marrakesh ePrix winner -Wiki-> y1]. Now search for when he was born [y1 -QA(When was Sébastien Buemi born ?)-> y2]. Now search for how many years after 1950 he was born so subtract [y2 - 1950 = y3]. The answer is y3.


### TASK
Now  generate C for the test examples below. Please Write '###DONE' when you have completed generating C for all of the examples below.
Respond in this format only:
Test Example <example number> C:

Test Example 1
Q: What year was id Tech 5 first used in a video game and how many languages was it originally available in?
A: 12
W: Id Tech 5 > <ref name="http://www.Gaminggroove.com posting"> </ref> id Tech 5 was first used in the video game "Rage", followed by "", "The Evil Within" and "". | Rage (video game) > Rage (stylized as RAGE) is a first-person shooter video game developed by id Software, released in October 2011.

Test Example 2
Q: What was the estimated population in 2017 of the city where the 2016 Rally Australia was held and what was its population in 1935 when it was first established?
A: 15
W: 2016 Rally Australia >  The race was held over four days between 17 November and 20 November 2016, and was based in Coffs Harbour, New South Wales, Australia. | Coffs Harbour >  It is one of the largest urban centres in the North Coast region, with an estimated population of 70,000 as of June 2017.

Test Example 3
Q: How many years after 1971 were both Johan Mjällby and Neil Lennon born?
A: 0
W: Johan Mjällby > Johan Mjällby (] ; born 9 February 1971) is a Swedish football manager and former player, currently in charge as manager of Västerås SK. | Neil Lennon > Neil Francis Lennon (born 25 June 1971) is a Northern Irish football coach and former player, who is the head coach of Scottish Premiership club Hibernian.

Test Example 4
Q: James McCartney was born on 12 September, which year was that after 1960?
A: 17
W: Close At Hand > Close At Hand is the second EP by James McCartney, son of Paul and Linda McCartney. | James McCartney > James Louis McCartney (born 12 September 1977) is a British musician and songwriter living in London.

Test Example 5
Q: In how many years since 1900 did Adelaide Central Plaza open?
A: 76
W: Adelaide Central Plaza > Adelaide Central Plaza is located on Rundle Mall, Adelaide. | Rundle Mall >  It was opened as a pedestrian mall in September 1976 by closing the section of Rundle Street between King William Street and Pulteney Street, to vehicular traffic.

Test Example 6
Q: William Patrick "Billy" Corgan Jr. was born on March 17, how many years after 1940 was it ?
A: 27
W: Monuments to an Elegy >  Band leader Billy Corgan has noted that—similar to the band's previous release, "Oceania"—the album is a part of the ongoing project, "Teargarden by Kaleidyscope". | Billy Corgan > William Patrick "Billy" Corgan Jr. (born March 17, 1967) is an American musician, songwriter, producer, poet, and entrepreneur.

Test Example 7
Q: What was the population at the 2000 census of the town where John Rais was born?
A: 22
W: John Rais >  Rais was born and raised in Burlington, Massachusetts, the youngest of seven children. | Burlington, Massachusetts >  The population was 24,498 at the 2010 census. | Burlington, Massachusetts >  The population was 22,183 at the 2000 census.

Test Example 8
Q: How many more years after 1940 does the fossil record of the order with the only strictly marine herbivorous mammal date back to?
A: 10
W: Evolution of sirenians >  Sirenians are thought to have a 50-million-year-old fossil record (early Eocene-recent). | Dugong >  It is one of four living species of the order Sirenia, which also includes three species of manatees. | Dugong >  The dugong is the only strictly marine herbivorous mammal.

Test Example 9
Q: Benjamin Hanby who wrote "Jolly Old Saint Nicholas" shared writing attribution with a poem written by Emily Huntington Miller, how many years after 1800 was the poem written?
A: 65
W: Benjamin Hanby > Benjamin Russell Hanby (July 22, 1833 – March 16, 1867), also given as Benjamin Russel Hanby, was an American composer, educator, and pastor who wrote approximately 80 songs. | Jolly Old Saint Nicholas > "Jolly Old Saint Nicholas" is a Christmas song that originated with a poem by Emily Huntington Miller (1833-1913), published as "Lilly's Secret" in "The Little Corporal Magazine" in December 1865. | Jolly Old Saint Nicholas >  The song's lyrics have also been attributed to Benjamin Hanby, who wrote a similar song in the 1860s, Up on the Housetop.

Test Example 10
Q: Visy Industries, founded in 1948 by Richard Pratt has since grown to be one of the world's largest privately owned paper, packaging and recycling companies, in how many complete years was it owned by Richard Pratt since its founding?
A: 61
W: Visy Industries >  Visy was owned by Richard Pratt until his death on 28 April 2009. | Richard Pratt (Australian businessman) > Richard J. Pratt (born Ryszard Przecicki; 10 December 193428 April 2009) was a prominent Australian businessman, chairman of the privately owned company Visy Industries, and a leading figure of Melbourne society.

### RESPONSE

In [130]:
paste_response="""
Test Example 1 C:
First search for [Euroinvestor -Wiki-> y1]. Search for the year the bank was established [y1 -QA(When was Euroinvestor established ?)-> y2]. Now find the year it would be 58 years old [y2 + 58 = y3]. The answer is y3.

Test Example 2 C:
First search for [Richard Godwin project -Wiki-> y1]. Search for the cost of the project [y1 -QA(What was the cost of the NS Savannah project ?)-> y2]. Now find the cost if it was 60% more expensive [y2 + (0.6 * y2) = y3]. The answer is y3.

Test Example 3 C:
First search for [Concord Naval Weapons Station -Wiki-> y1]. Search for the year it was established [y1 -QA(When was Concord Naval Weapons Station established ?)-> y2]. Now find the year it would be 100 years old [y2 + 100 = y3]. The answer is y3.

Test Example 4 C:
First search for [Princess Maria-Olympia of Greece and Denmark -Wiki-> y1]. Search for the year Constantine II was last king of Greece [y1 -QA(When was Constantine II the last king of Greece ?)-> y2]. Now find the year multiplied by 2 [1973 * 2 = y3]. The answer is y3.

Test Example 5 C:
First search for [Get Rich or Die Tryin' (film) -Wiki-> y1]. Now search for the artist's name [y1 -QA(Who starred in Get Rich or Die Tryin' ?)-> y2]. Search for the number of nominations at the 54th Grammy Awards [y2 -QA(How many Grammy Awards nominations did 50 Cent receive for the soundtrack ?)-> y3]. The answer is y3.

Test Example 6 C:
First search for [Three Hundred Big Boys Futurama -Wiki-> y1]. Now search for the director of the episode [y1 -QA(Who directed Three Hundred Big Boys ?)-> y2]. Now search for the number of segments in the episode [y1 -QA(How many segments are there in Three Hundred Big Boys ?)-> y3]. The answer is y3.

Test Example 7 C:
First search for [Tekno Team 2000 -Wiki-> y1]. Now search for Erik Watts birth year [y1 -QA(When was Erik Watts born ?)-> y2]. Search for the number of championships won [y1 -QA(How many championships did Tekno Team 2000 win ?)-> y3]. The answer is y3.

Test Example 8 C:
First search for [Joseph Smith (explorer) -Wiki-> y1]. Now search for the year York Factory was built [y1 -QA(When was York Factory built ?)-> y2]. Now find the number of locations it had when it was first used [y1 -QA(How many locations did York Factory have when it was first used ?)-> y3]. The answer is y3.

Test Example 9 C:
First search for [Saw 3D -Wiki-> y1]. Now search for the release year of the movie [y1 -QA(When was Saw 3D released ?)-> y2]. Search for the number of releases that week [y1 -QA(How many times was Saw 3D released that week ?)-> y3]. The answer is y3.

Test Example 10 C:
First search for [Donald Cammell -Wiki-> y1]. Now search for Peter Bogdanovich birth year [y1 -QA(When was Peter Bogdanovich born ?)-> y2]. Find the age of Donald Cammell if he were still alive today [current year - 1996 = y3]. Find the age of Peter Bogdanovich if he were still alive today [current year - y2 = y4]. Find the difference in their ages [y3 - y4 = y5]. The answer is y5.

###DONE


"""

In [131]:
paste_response=paste_response.replace("C:\n","C:")
contents = re.findall(r'C:(.*)', paste_response)
if len(contents)==10:
  print('FOUND ALL 8')
  # Add each element of content to the corresponding row
  for i, row in enumerate(selected_rows):
      row['C'] = contents[i].strip()

FOUND ALL 8

In [132]:
generated_dataset.extend(selected_rows)

In [133]:
len(generated_dataset)

200

In [136]:
generated_dataset

[{'Q': 'How many countries that are not Member states of the Commonwealth of Nations utilize English as a sole official language or one of the official languages?',
  'A': '10',
  'W': 'English in the Commonealth of Nations > The use of the English language in most member countries of the Commonwealth of Nations was inherited from British colonisation. | English in the Commonealth of Nations >  English is spoken as a first or second language in most of the Commonwealth. | English in the Commonwealth of Nations >  In a few countries, such as Cyprus and Malaysia, it does not have official status, but is widely used as a lingua franca. | English in the Commonwealth of Nations >  Mozambique is an exception – although English is widely spoken there, it is a former Portuguese colony which joined the Commonwealth in 1996. | List of countries where English is an official language > In addition to the 26 Commonwealth of Nations, there are 10 other countries where English is an official language.',
  'C': 'First search for [List of countries where English is an official language -Wiki-> y1]. Now search for the number of countries where English is an official language [y1 -QA(How many countries have English as an official language ?)-> y2]. The answer is y2.'},
 {'Q': 'In how many more years since 2000 has Amber Calling been active compared to their supporting act?',
  'A': '15',
  'W': 'Amber Calling >  During their career they have supported shows by Grinspoon, Kenny Vasoli, Panic! | Panic! at the Disco >  at the Disco is an American rock band from Las Vegas, Nevada, formed in 2004 and featuring the current lineup of vocalist Brendon Urie, accompanied on tour by bassist Dallon Weekes, guitarist Kenneth Harris and drummer Dan Pawlovich. | Amber Calling >  The band was formed in Adelaide, Australia in 2005 and consists of vocalist Ethan McCarthy, guitarist Michael Prins, bassist Oliver Powers and drummer Jayden Walker.',
  'C': 'First search for [Amber Calling -Wiki-> y1]. Now search for when the band was formed [y1 -QA(When was Amber Calling formed ?)-> y2]. Now search for the formation year of Panic! at the Disco [Panic! at the Disco -Wiki-> y3]. Now find the difference in years [y2 - y3 = y4]. The answer is y4.'},
 {'Q': 'How many years after Michael Essien graduated from the SC Bastia Reserves and Academy was John Laub born?',
  'A': '21',
  'W': 'SC Bastia Reserves and Academy >  Notable graduates of the academy include Alex Song, Michael Essien, Nicolas Penneteau, Yannick Cahuzac, Wahbi Khazri, Claude Papi and Charles Orlanducci. | Michael Essien > Michael Kojo Essien (born 3 December 1982) is a Ghanaian footballer who currently plays for Indonesian club Persib Bandung. | John Laub > John H. Laub (born 1953) is an American criminologist and Distinguished University Professor in the Department of Criminology and Criminal Justice at the University of Maryland, College Park.',
  'C': 'First search for [SC Bastia Reserves and Academy -Wiki-> y1]. Now search for when Michael Essien graduated [y1 -QA(When did Michael Essien graduate from SC Bastia Reserves and Academy ?)-> y2]. Now search for when John Laub was born [John Laub -Wiki-> y3]. Now find the difference in years [y2 - y3 = y4]. The answer is y4.'},
 {'Q': 'In what year was the founder of the University of Maryland, College Park, who was forced to resign five years after due to poor academic and administrative performance, born?',
  'A': '1785',
  'W': "University of Maryland, College Park > The University of Maryland, College Park (often referred to as the University of Maryland, Maryland, UM, UMD, UMCP, or College Park) is a public research university located in the city of College Park in Prince George's County, Maryland, approximately 4 mi from the northeast border of Washington, D.C. Founded in 1856, the university is the flagship institution of the University System of Maryland. | University of Maryland, College Park >  The university was founded in 1856 as the Maryland Agricultural College by a group of farmers and businessmen who believed that the state needed an institution to teach agriculture and the mechanical arts. | University of Maryland, College Park >  Its first president was Reverdy Johnson, who resigned five years later due to poor academic and administrative performance.",
  'C': 'First search for [University of Maryland, College Park founder -Wiki-> y1]. Now search for when the founder was born [y1 -QA(When was the founder of the University of Maryland, College Park born ?)-> y2]. The answer is y2.'},
 {'Q': 'When did the king who transferred Schottenkirche to German-speaking Benedictine monks die?',
  'A': '27',
  'W': 'Schottenkirche, Vienna >  In 1418, the Duke Albert V of Austria transferred it to the German-speaking Benedictine monks from the Melk Abbey during the Melker Reform initiated after the Council of Constance. | Albert II of Germany > Albert the Magnanimous KG (10 August 139727 October 1439) was King of Hungary and Croatia from 1437 until his death.',
  'C': 'First search for [Schottenkirche, Vienna -Wiki-> y1]. Now search for who transferred it to German-speaking Benedictine monks [y1 -QA(Who transferred Schottenkirche to German-speaking Benedictine monks ?)-> y2]. Now search for when Albert II of Germany died [Albert II of Germany -Wiki-> y3]. Now find the difference in years [y3 - y2 = y4]. The answer is y4.'},
 {'Q': 'How many days after the debut of Jon Flanagan for Liverpool, was his uncle born?',
  'A': '3638',
  'W': 'Bradley Orr > Bradley James Orr (born 1 November 1982) is an English retired footballer. | Bradley Orr >  He is the uncle of the Liverpool F.C. full back Jon Flanagan. | Jon Flanagan >  He made his debut for Liverpool in a 3–0 win against Manchester City on 11 April 2011 at age 18.',
  'C': 'First search for [Jon Flanagan debut date -Wiki-> y1]. Now search for when his uncle was born [Bradley Orr -Wiki-> y2]. Now find the difference in days [y1 - y2 = y3]. The answer is y3.'},
 {'Q': 'In what year did an English professional snooker player from Leicester win the China Open?',
  'A': '1997',
  'W': 'China Open (snooker) > The China Open is a professional snooker tournament. | China Open (snooker) >  It is one of a number of ranking tournaments and began in 1997. | Mark Selby > Mark Anthony Selby (born 19 June 1983) is an English professional snooker player from Leicester.',
  'C': 'First search for [China Open (snooker) -Wiki-> y1]. Now search for when Mark Selby was born [Mark Selby -Wiki-> y2]. Now find the year when China Open started [y1 -QA(When did China Open start ?)-> y3]. Now find the difference in years [y3 - y2 = y4]. The answer is y4.'},
 {'Q': 'How many more years passed after the 17th Street Canal was built until the Champlain Canal was built?',
  'A': '122',
  'W': '17th Street Canal > The 17th Street Canal is the largest and most important drainage canal in the city of New Orleans. | Champlain Canal > The Champlain Canal is a 60 mi canal that connects the south end of Lake Champlain to the Hudson River in New York.',
  'C': 'First search for [17th Street Canal -Wiki-> y1]. Now search for when the Champlain Canal was built [Champlain Canal -Wiki-> y2]. Now find the difference in years [y2 - y1 = y3]. The answer is y3.'},
 {'Q': 'How many years before 2017 was YSR Congress Party formed from INC? ',
  'A': '2',
  'W': 'Kayithi Narsi Reddy > Kayithi Narsi Reddy is an Indian politician initially associated with INC and then with YSR Congress Party. | Indian National Congress >  Founded in 1885, it was the first modern nationalist movement to emerge in the British Empire in Asia and Africa.',
  'C': 'First search for [YSR Congress Party formation -Wiki-> y1]. Now search for when INC was founded [Indian National Congress -Wiki-> y2]. Now find the difference in years [y1 - y2 = y3]. The answer is y3.'},
 {'Q': 'The 1965 Nebraska Cornhuskers football team was formed how many years before 1965?',
  'A': '58',
  'W': '1965 Nebraska Cornhuskers football team > The 1965 Nebraska Cornhuskers football team was the representative of the University of Nebraska and member of the Big Eight Conference in the 1965 college football season. | Big Eight Conference >  It was formed in January 1907 as the Missouri Valley Intercollegiate Athletic Association (MVIAA) by its charter member schools: the University of Kansas, University of Missouri, University of Nebraska, and Washington University in St. Louis.',
  'C': 'First search for [1965 Nebraska Cornhuskers football team -Wiki-> y1]. Now search for when the team was formed [y1 -QA(When was the 1965 Nebraska Cornhuskers football team formed ?)-> y2]. Now find the difference in years [1965 - y2 = y3]. The answer is y3.'},
 {'Q': 'In how many years after 1917 the Imperial War Museum become the Imperial War Museums?',
  'A': '3',
  'W': "Forgotten Voices of the Great War > Forgotten Voices of the Great War is a collection of interviews with people who lived through the First World War. | Forgotten Voices of the Great War >  The book is part of the Imperial War Museum's oral archive. | Imperial War Museum > Imperial War Museums (IWM) is a British national museum organisation with branches at five locations in England, three of which are in London. | Imperial War Museum >  Founded as the Imperial War Museum in 1917, the museum was intended to record the civil and military war effort and sacrifice of Britain and its Empire during the First World War.",
  'C': 'First search for [Imperial War Museum -Wiki-> y1]. Search for its founding year [y1 -QA(When was the Imperial War Museum founded ?)-> y2]. Number of years after 1917 it became Imperial War Museums [y2 - 1917 = y3]. The answer is y3.'},
 {'Q': "Buddymoon was written in part by Flula Borg, who was named one of the Hollywood Reporter's top 25 digital stars how many years after 2011?",
  'A': '4',
  'W': 'Buddymoon > Buddymoon (previously known as Honey Buddies) is a 2016 American independent comedy film directed by Alex Simmons; written by Simmons, Flula Borg, and David Giuntoli; and starring Borg and Giuntoli. | Flula Borg > Flula Borg (born March 28, 1982) is a German actor, comedian, musician, and YouTube personality who is better known as DJ Flula or simply Flula (sometimes stylized as f|u|a). | Flula Borg >  Borg has appeared in several feature films, including "Pitch Perfect 2", and a number of popular TV shows. | Flula Borg >  In 2015, he was named one of The Hollywood Reporter\'s Top 25 Digital Stars as well as one of Variety\'s 10 Comics to Watch.',
  'C': "First search for [Flula Borg -Wiki-> y1]. Now find when he was named in The Hollywood Reporter's Top 25 Digital Stars [y1 -QA(When was Flula Borg named in The Hollywood Reporter's Top 25 Digital Stars ?)-> y2]. Number of years after 2011 he was named in that list [y2 - 2011 = y3]. The answer is y3."},
 {'Q': 'How many more aircraft designs did Sikorsky make between the S-1 and S-2?',
  'A': '1',
  'W': 'Sikorsky S-1 > The Sikorsky S-1 was the first fixed wing aircraft design by Igor Sikorsky. | Sikorsky S-1 >  Further attempts were less successful and Sikorsky disassembled it saving the main wing section to construct the S-2. | Igor Sikorsky > Igor Ivanovich Sikorsky (Russian: И́горь Ива́нович Сико́рский ; ] , "Ígor\' Ivánovič Sikórskij"; , "Ihor Ivanovych Sikorskyi"; May 25, 1889 – October 26, 1972), was a Russian-American aviation pioneer in both helicopters and fixed-wing aircraft. | Igor Sikorsky >  First success came with the S-2, the second aircraft of his design and construction.',
  'C': 'First search for [Sikorsky S-1 -Wiki-> y1]. Now search for what aircraft design came after S-1 [y1 -QA(What came after Sikorsky S-1 ?)-> y2]. Number of additional aircraft designs between S-1 and S-2 [y2 - 1 = y3]. The answer is y3.'},
 {'Q': 'In how many years will there be 30 years from the date of publication of Stephen King\'s novel "11/22/63"?',
  'A': '9',
  'W': 'Mile 81 >  The publication also includes an excerpt from King\'s novel "11/22/63", published two months later. | 11/22/63 >  The novel was published on November 8, 2011 and quickly became a number-one bestseller.',
  'C': 'First search for [11/22/63 publication date -Wiki-> y1]. Now find the publication year [y1 -QA(When was 11/22/63 novel published ?)-> y2]. Number of years until there are 30 years from the publication date [y2 + 30 = y3]. The answer is y3.'},
 {'Q': 'If KBS2 show 2 Days & 1 Night adds 2 more members, then what will be the total number of cast members?',
  'A': '8',
  'W': '2 Days &amp; 1 Night > 2 Days & 1 Night (; also known as 1 Night 2 Days; abbreviated as 1N2D) is a South Korean reality-variety show that airs on KBS2 beginning August 5, 2007. | 2 Days &amp; 1 Night >  The show\'s current cast members are Kim Jong-min, Cha Tae-hyun, Kim Joon-ho, Defconn, Yoon Shi-yoon, and Jung Joon-young. | Jung Joon-young >  Since 2015, Jung is the lead vocalist of rock band Drug Restaurant, previously known as JJY Band, releasing their first album "Escape to Hangover" in May 2015',
  'C': 'First search for [2 Days & 1 Night -Wiki-> y1]. Search for the number of current cast members [y1 -QA(How many cast members does 2 Days & 1 Night have ?)-> y2]. If 2 more members are added, the total number of cast members [y2 + 2 = y3]. The answer is y3.'},
 {'Q': 'That\'s My Mommy is one reel animated "Tom and Jerry" short, there are how many reels in a regular animated "Tom and Jerry" short?',
  'A': '1',
  'W': 'That\'s My Mommy > That\'s My Mommy is a 1955 one reel animated "Tom and Jerry" short directed and produced by William Hanna and Joseph Barbera with music by Scott Bradley. | Tom and Jerry > Tom and Jerry is an American animated series of short films created in 1940, by William Hanna and Joseph Barbera.',
  'C': 'First search for [Tom and Jerry -Wiki-> y1]. Now search for the number of reels in a regular animated "Tom and Jerry" short [y1 -QA(How many reels are there in a regular Tom and Jerry short ?)-> y2]. The answer is y2.'},
 {'Q': 'What is Chinese name for the science fiction prequel to an American neo-noir science fiction film directed by Denis Villeneuve divided by two?',
  'A': '1024',
  'W': '2048: Nowhere to Run > 2048: Nowhere to Run (known in Chinese and Taiwanese territories as 2048: No Escape or 2048: Nowhere to Escape; alteratively known as Blade Runner 2048) is a 2017 American neo-noir science fiction short film acting as a prequel to the feature film "Blade Runner 2049" and the sequel to short film ""; it was released on August 30, 2017, less than one month before the release of the feature film, and features Dave Bautista as "Blade Runner 2049" character Sapper Morton, alongside Orion Ben. | Blade Runner 2049 > Blade Runner 2049 is an upcoming American neo-noir science fiction film directed by Denis Villeneuve and written by Hampton Fancher and Michael Green.',
  'C': 'First search for [2048: Nowhere to Run -Wiki-> y1]. Now search for the name in Chinese [y1 -QA(What is the Chinese name for 2048: Nowhere to Run ?)-> y2]. Number of times it needs to be divided by 2 [1024 / 2 = y3]. The answer is y3.'},
 {'Q': 'The inner urban neighbourhood Eureka Tower is in had a population of what in 2011, subtract the population of Easter island?',
  'A': '8149',
  'W': "Eureka Tower > Eureka Tower is a 297.3 m skyscraper located in the Southbank precinct of Melbourne, Victoria, Australia. | Southbank, Victoria > Southbank is an inner urban neighbourhood of Melbourne, Victoria, Australia, 1 km south of Melbourne's central business district. | Southbank, Victoria >  Its local government area are the Cities of Melbourne and Port Phillip. | Southbank, Victoria >  At the 2011 Census, Southbank had a population of 11,235. | Easter Island > Easter Island, or Rapa Nui, is a Chilean island in the southeastern Pacific Ocean, at the southeasternmost point of the Polynesian Triangle. | Easter Island >  The island has a population of 5,832, of whom 60.2% live in the city of Hanga Roa.",
  'C': 'First search for [Southbank, Victoria population 2011 -Wiki-> y1]. Now search for the population of Easter Island [Easter Island -Wiki-> y2]. Number of population in 2011 minus the population of Easter Island [y1 - y2 = y3]. The answer is y3.'},
 {'Q': 'The film To Hell and Back stars a combat solider that received the Medal of Honor at what age, multiply by 10?',
  'A': '190',
  'W': 'To Hell and Back (film) >  It was directed by Jesse Hibbs and starred Audie Murphy as himself. | Audie Murphy >  Murphy received the Medal of Honor for valor demonstrated at the age of 19 for single-handedly holding off an entire company of German soldiers for an hour at the Colmar Pocket in France in January 1945, then leading a successful counterattack while wounded and out of ammunition.',
  'C': 'First search for [To Hell and Back -Wiki-> y1]. Now search for the age at which Audie Murphy received the Medal of Honor [y1 -QA(At what age did Audie Murphy receive the Medal of Honor ?)-> y2]. Multiply the age by 10 [y2 * 10 = y3]. The answer is y3.'},
 {'Q': 'This British scholar who attended the oldest English-speaking university in the English speaking world was a president of the British academy for what length of time, subtract age of Maria Theresa at her coronation?',
  'A': '4',
  'W': "Denys Page > Sir Denys Lionel Page, FBA (11 May 1908, Reading, Berkshire – 6 July 1978, Tarset) was a British classical scholar at Oxford and Cambridge universities. | Denys Page >  He was President of the British Academy from 1971–74. | University of Oxford > The University of Oxford (informally Oxford University or simply Oxford) is a collegiate research university located in Oxford, England. | University of Oxford >  It has no known date of foundation, but there is evidence of teaching as far back as 1096, making it the oldest university in the English-speaking world and the world's second-oldest university in continuous operation. | Maria Theresa > Maria Theresa (13 May 1717 – 29 November 1780) was the only female ruler of the Habsburg dominions and the last of the House of Habsburg.",
  'C': 'First search for [Denys Page -Wiki-> y1]. Now find the length of time he was President of the British Academy [y1 -QA(How long was Denys Page President of the British Academy ?)-> y2]. Now search for the age of Maria Theresa at her coronation [Maria Theresa -Wiki-> y3]. Subtract her age from the length of time Denys Page was President [y2 - y3 = y4]. The answer is y4.'},
 {'Q': 'In what year did Brian Hugh Warner perform on MTV Europe Music Awards, add 100?',
  'A': '2099',
  'W': '1999 MTV Europe Music Awards > The 1999 MTV Europe Music Awards were held in Dublin, Ireland at The Point. | 1999 MTV Europe Music Awards >  Ronan Keating returned as host, with performers including Mariah Carey singing "Heartbreaker", Britney Spears with "...Baby One More Time" & "(You Drive Me) Crazy", as well as The Cardigans, Jamiroquai, Marilyn Manson and The Corrs and show opener Iggy Pop. | Marilyn Manson > Brian Hugh Warner (born January 5, 1969), known professionally as Marilyn Manson, is an American singer, songwriter, musician, composer, actor, painter, author and former music journalist.',
  'C': 'First search for [Brian Hugh Warner MTV Europe Music Awards -Wiki-> y1]. Search for year he performed [y1 -QA(When did Brian Hugh Warner perform on MTV Europe Music Awards ?)-> y2]. Add 100 to the year [y2 + 100 = y3]. The answer is y3.'},
 {'Q': 'On what date was the album first issued whose outtakes provided the first four tracks on the album The Unissued Johnny Cash, add 10 years?',
  'A': '1968',

In [ ]:
## at the end save generated dataset

In [138]:
df = pd.DataFrame(generated_dataset)
df.to_pickle('/content/drive/MyDrive/NLP_project/abhishek2.pkl')

## MUKTI_TOOL ABHISHEK

In [ ]:
df1 = pd.read_pickle("/content/drive/MyDrive/NLP_project/Abhishek (Mutli tool Chained- hotpot)/First_QAWC.pkl")
df1